name: Chocolatine Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run coding style checker
        run: ghcr.io/epitech/coding-style-checker:latest check.sh $(pwd) $(pwd)

  check_program_compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile program
        run: make
      - name: Clean up
        run: make clean
      - name: Verify executables
        run: |
          for executable in $(echo $EXECUTABLES | tr "," "\n")
          do
            if [ ! -x "$executable" ]; then
              echo "Executable $executable not found or not executable"
              exit 1
            fi
          done

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: make tests_run

  push_to_mirror:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.repository != secrets.MIRROR_URL
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push to mirror
        run: |
          git push $MIRROR_URL
        env:
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

env:
  MIRROR_URL: git@github.com:marien272/chocolatine2.git
  EXECUTABLES: mygoat
